language: node_js

node_js:
  - '7'

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - yarn add @angular/cli

script:
  - ng test --code-coverage --watch=false
  - ng lint --type-check

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: s3
  access_key_id:
  secret_access_key:
  bucket: "cru-mobilecontentadmin-staging"
  region: us-east-1
  skip_cleanup: true
  local_dir: dist
  acl: public_read

cache:
  yarn: true
  directories:
  - node_modules

notifications:
  email: false
