language: node_js
node_js: '10'
env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAIMLCVOS5TLNZVNSA
    - secure: D+eq9JjLJ8ZMOGJbIsgCziGSwJuyLx6z4lytacrer/G5/33g4LuT2e950bLMyETjyemhRu1XrnI9DEsCKgyhBtcmKYvcb1dqXwdBcaYpWQ7yfl8f9kdfnhwcQpr4rk4u9/mf0UnRDZUk7ha9MNGvHxMpbluaUIwgPjn+ITdAyhDbtXLshSDrIWUwqyfhswm4uj0WJTMoPRrKCHthoeYMqmP92evGVy0CimQCzhveo4syJQlA7ubDRbh+q/wrGvgbRSazButAwLqMmNF9DJWwRcUKSOZ8t75+Hr4QnCu50hZALxWePPIEWcnIPCNRRVlhfv8ajIPmeAwrOKmTAmPbNW+0uSg9WoolzGux1D74sWCZDFTvpBtjMwCtu/blmcfmYlwDY2qg0U1sS7pSSUBSYAO5sILw5cRH3lGfRBOFlnOUOC+fQl0n7ul3H7ZfnibJRlbZIbL7/BSdKQKRuZAAU5Hv+BkJRfdRHnGKfjWHA2idei1SVit/7+k/Gi4NGyu21mAHSnyc9NwR+4+u6e6WT3Lq09R2CpK5avjKez25t+vmBMqvwn/br5NfWTIf3B4Z0b/JTdLdIrO6m0Qdej59UQZ8Hf8qAQew5/bW1he6DLUhWzwFTksQYlty1PEo5dkiH5Yk9qzc9Fqs1S/qhIeK10X3VH8LYUW+iGY8b64v1JY=

addons:
  chrome: stable

services:
  - xvfb

stages:
  - name: test
  - name: release
    if: type = push

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: test

      before_install:
        - export CHROME_BIN=/usr/bin/google-chrome

      script:
        - ng test --watch=false --code-coverage
        - ng lint --type-check
        - yarn prettier:check
        - ng build -c staging
        - ng build -c production

      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - name: 'Release Staging'
      stage: release
      if: branch = staging

      script: ng build -c staging

      deploy:
        - provider: s3
          bucket: 'cru-mobilecontentadmin-staging'
          region: us-east-1
          skip_cleanup: true
          local_dir: dist
          acl: public_read
          on:
            branch: staging

    - name: 'Release Production'
      stage: release
      if: branch = master

      script: ng build -c production

      deploy:
        - provider: s3
          bucket: 'cru-mobilecontentadmin-prod'
          region: us-east-1
          skip_cleanup: true
          local_dir: dist
          acl: public_read
          on:
            branch: master

notifications:
  email: false
