language: node_js

node_js:
  - '7'

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - yarn add @angular/cli

script:
  - ng test --code-coverage --watch=false
  - ng lint --type-check

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: s3
  access_key_id:
  secret_access_key:
  bucket: "cru-mobilecontentadmin-staging"
  region: us-east-1
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  on:
    all_branches: true

cache:
  yarn: true
  directories:
  - node_modules

notifications:
  email: false
env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAIMLCVOS5TLNZVNSA
    secure: tlA885OkaJzVhP9iC1LWCKRQebNG0p/0ifnHxdzXy93C0zZ9413Uxs+Jau4TNGWXp1SaiEeEI58xme7pw4PDgXJHNDknGmXJpfDxfiVSgQSeDVdJ6iYfNYI4m5IukIhuirp8gkwvrH7nV2rV6A9V5AnyF94oceVWbsFdlsV5cJ7O+1v47FQ93S4IfIQTzu2KCNLaxHW18yi0prwoSaMHKBHTTpz7AjES4EstZ94y7xrxKTxTxRvDDZJiGIzg1sMOTWyYN9DX6EoSCoIpzMXASMxDDGos0uh2GW3zk+2aN68h+4Ie4B7W+D1e/U8C4GbIhFQNRD0lJDYARDQgf7UHlCYiwagF5zNqGGUhTAwcb33vVC+lRC3QmlYKid090hB5QT1pstGIjve3RhfRZft3u/kuw8BEu7t5kl1RTtMVXrV82v89nZuGpPJTDaAujZkZ/EKvQOI70MarKdXWXlFC5BsaBKN7WWromepfPpLesVJ1kBkD+z7TZxnVLbVX27hcpX4EKEk7UqqcvlA62T4MS4q6MJ6MqqSd3zM1ymfiLbph7P1PrJhXzciMAzDXJT+ktc/B4MzUgcxVuTgiEUsEGTHKTfhHGFPddHTsBg3z4jNB8MenmJoRPCfeH/EKxkviBOBRv58sQfXjG5v4JC4oSdWUWByC5volXZGlj2GqVBY=
