name: CI

on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [master, staging]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CHROME_BIN: /usr/bin/google-chrome

permissions:
  id-token: write
  contents: write

jobs:
  test:
    name: Checks & Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install Dependenices
        run: npm install
      - name: Run Test with CodeCov
        env:
          CHROME_BIN: /usr/bin/google-chrome
        run: npm run test:codecov
      - name: Run Lint & Prettier Tests
        run: |
          npm run lint:type
          npm run prettier:check
      - name: Build staging
        run: npm run build:stage
      - name: build production
        run: npm run build:prod
      - name: Code coverage test
        if: success()
        uses: codecov/codecov-action@v1.1.1

  deployStaging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
    environment: stage
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install Dependenices
        run: npm install
      - name: Build Staging
        run: npm run build:stage
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: '${{ secrets.AWS_IAM_ROLE_ARN }}'
          aws-region: us-east-1
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }} --region us-east-1 --acl public-read --cache-control "max-age=300"

  deployProduction:
    name: Deploy Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    environment: prod
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install Dependenices
        run: npm install
      - name: Build Production
        run: npm run build:prod
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }} --region us-east-1 --acl public-read --cache-control "max-age=300"
